version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/ready" ]
      interval: 5s
      timeout: 3s
      retries: 5
    command: ["server", "/data", "--console-address", ":9090"]
  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-admin} # default value 'admin'
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-admin123} # default value 'admin123'
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 \"$MINIO_ACCESS_KEY\" \"$MINIO_SECRET_KEY\" &&
        mc mb local/music || echo 'bucket exists';
      "
volumes:
  minio-data: